version: '3.2'

networks:
  default-network:
    external: true

services:

  postgres:
    image: postgres:11
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DB}"
    networks:
      - default
      - default-network

  php-backend:
    build:
      context: .
      dockerfile: docker/php/backend/Dockerfile
    ports:
      - 21080:80
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
      - "phpsocket:/var/run"
    depends_on:
      - postgres
    environment:
      - DB_DSN
      - DB_DB
      - DB_USERNAME
      - DB_PASSWORD
      - DB_PORT
      - MAILER_HOST
      - MAILER_USERNAME
      - MAILER_PASSWORD
      - MAILER_PORT
      - MAILER_ENCRYPTION
    networks:
      - default

  php-frontend:
    build:
      context: .
      dockerfile: docker/php/frontend/Dockerfile
    ports:
      - 20080:80
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
      - "phpsocket:/var/run"
    depends_on:
      - postgres
    environment:
      - DB_DSN
      - DB_DB
      - DB_USERNAME
      - DB_PASSWORD
      - DB_PORT
      - MAILER_HOST
      - MAILER_USERNAME
      - MAILER_PASSWORD
      - MAILER_PORT
      - MAILER_ENCRYPTION
    networks:
      - default

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - "phpsocket:/var/run"
      - ./:/app
      - "./docker/nginx/nginx.conf.template:/etc/nginx/
    environment:

    command: /bin/bash -c "envsubst < /etc/nginx/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - php-backend
      - php-frontend
    networks:
      - default

volumes:
  phpsocket: