version: '3.2'

networks:
  default-network:
    external: true

services:

  postgres:
    image: postgres:11
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DB}"
    networks:
      - default
      - default-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    ports:
      - 20080:80
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
      - "phpsocket:/var/run"
    depends_on:
      - postgres
    environment:
#      - ENVIRONMENT
      - DB_DSN
      - DB_DB
      - DB_USERNAME
      - DB_PASSWORD
      - DB_PORT
      - MAILER_HOST
      - MAILER_USERNAME
      - MAILER_PASSWORD
      - MAILER_PORT
      - MAILER_ENCRYPTION
    networks:
      - default

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - "phpsocket:/var/run"
      - ./:/app
    environment:
      - ENV_DOMAIN
      - ENV_FRONTEND_PREFIX
      - ENV_BACKEND_PREFIX
    command: /bin/bash -c "envsubst '$$ENV_DOMAIN $$ENV_FRONTEND_PREFIX $$ENV_BACKEND_PREFIX' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      - php
    networks:
      - default

volumes:
  phpsocket: